### ISSUE TITLE
Use your source for an external app for another space sim

### ISSUE THREAD

**Issue by BGASM** [mycumycu/X4-External-App#1]
Hey! This is a really cool tool. I've been working on the source privately to hook it onto the output from another space sim called Evochron Legacy to track market price changes and current ship loadout. I don't know if I will work on it to full release capacity, but I have attributed you in all the source files so far.

Would you mind if I released it to the public, if I get it to that point?

Thanks a lot. Great work by the way! I used SirNukesPipes to make a market compare tool for X4 a few years ago, but it was an ugly ugly mess. This looks gorgeous.

My repo has the external app set as private for now, but I sent you a collab invite if you wanted to see what up.

**Comment by mycumycu** [comment]
Hey :)
I haven't had a chance to play Evochron Legacy yet (although I used to plan to) but it's cool that you're modding it.

Feel free to use my code in your project. 
I'm curious to see where your project will lead.

Good luck!
