### ISSUE TITLE
Filters: Featured filters override exclude filters if placed above

### ISSUE THREAD

**Issue by al1-ce** [mycumycu/X4-External-App#10]
If to set filter "Info" - Featured and after it set "mining" - Exclude, then mining info will still show, if to set mining filter first then it functions correctly

**Comment by mycumycu** [comment]
Do you mean such filter setup?

![image](https://github.com/mycumycu/X4-External-App/assets/33801919/ae3e2c7e-9df3-4e20-9a7e-8b7615e25651)

With that setup the excluded data was correctly filtered out.

**Comment by al1-ce** [comment]
I'll try replicating bit later, will attach some screenshots
