### ISSUE TITLE
Little gotcha

### ISSUE THREAD

**Issue by aefreedman** [mycumycu/X4-External-App#2]
Hiya, super cool mod, excited to play around with it :) 

Apparently the external app pipe doesn't start until either you unpause the game or interact with the menu and move off the settings tab after the game loads. This confused me during install and I thought it was broken. Might want to mention this in the install instructions.

The extension info window in-game for the Named Pipes will also always show x4_external_app as "disconnected", even when it is working properly.

**Comment by mycumycu** [comment]
Hey Aaron, thanks for the feedback. 
Yeah, the external app does not receive data until game is loaded and unpaused once. I will make "there's no water" message more precise with next update. 
Named Paipes will show "disconnected" until then - becuase it connects on first data received.
