### ISSUE TITLE
Seems to be having stability issues with 6.0

### ISSUE THREAD

**Issue by GameBurrow** [mycumycu/X4-External-App#6]
After th 6.0 update the external app seems to be quite unstable for some strange reason, especially when a lot is going on around you.

Sometimes for  quite some time it just keeps reconnecting:
![image](https://user-images.githubusercontent.com/4341091/235315591-d89a07d6-61ca-45e8-bfe1-93cb7da88c9b.png)

**Comment by mycumycu** [comment]
Thank you for reporting. 
I didn't managed to play 6.0 yet - so it's harder for me to recreate/fix it just yet - but it should get better soon.

**Comment by mycumycu** [comment]
Can you test if 2.2.3 version fixes it for you?

**Comment by GameBurrow** [comment]
> Can you test if 2.2.3 version fixes it for you?

Will check next week

**Comment by aurism** [comment]
@mycumycu thank you for this great app! I see this problem in version 2.2.3 unfortunately.

**Comment by GameBurrow** [comment]
> Can you test if 2.2.3 version fixes it for you?

I had time for one few hour game session. During that period I didn't encounter the bug yet.

> @mycumycu thank you for this great app! I see this problem in version 2.2.3 unfortunately.

@aurism Just to make sure did you update both the mod itself and the app .exe?

**Comment by aurism** [comment]
@GameBurrow I had updated the app but not the mod when the errors occurred, that might explain it! After updating the mod, so far seems to be working, will report back if that changes.

**Comment by GameBurrow** [comment]
I'll close it now as at least I personally haven't noticed the issue anymore. Thank you for your work @mycumycu
