### ISSUE TITLE
Compatibility with coloring names mods?

### ISSUE THREAD

**Issue by darkfr3ak** [mycumycu/X4-External-App#7]
Hey. I absolutely love this app! I haven't encountered any bugs with 6.0 yet, but i've found a small "problem".

The Mission Offers widget shows missions like this

`Escort #ffbcd0fb#TER Agricultural Trader Baldric`

Would it be possible to either remove the color code or use it to color the ships name? I am using the ["Colourized Faction Texts"](https://www.nexusmods.com/x4foundations/mods/1019) mod right now.

Thank you!

**Comment by mycumycu** [comment]
It's possible to add support for such color strings. Can't give any ETA tho:)

**Comment by Coyote21** [comment]
+1

Hoping, (not expecting) a +1 encourages you, knowing there is more than 1 person hoping for this feature.

**Comment by Coyote21** [comment]
Little snooping and some regular expression knowledge and I found a temp workaround if you need.

Needs a little coding experience (but not much).

Problem is in src/widgets/mission_offers/MissionOffersMission.vue

Line 42:  `return text.replace(/<[^>]*>?/gm, '')`

Change to:  `return text.replace(/(<[^>]*>?|#[^#]*#?)/gm, '')`

This will remove the hex codes from the text, but does not make the text sexy and coloured, I'll leave that to mycumycu 'cause I can recognise/edit regular expressions but know nothing about node.js code.

You will need to recompile after making the edit, follow the instructions at the bottom of the readme.

**Comment by mycumycu** [comment]
Thanks @Coyote21 for a regexp.
This will be implemented in next version.

**Comment by mycumycu** [comment]
Version 2.3.0 is live now.
