### ISSUE TITLE
Compatibility issues with VPNs

### ISSUE THREAD

**Issue by Coyote21** [mycumycu/X4-External-App#8]
First time trying this on Win10, I was getting a quick flash of console then nothing. Executing from a command line showed me the issue:

```
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: Could not find default gateway route in routing table.
```
Dis-connecting my VPN client fixes the issue.

Would be useful if I could give the relevant network info as command line arguments, or in a config file instead.

NOTE: I'm only really using my VPN now b/c I'm (unreasonably?) paranoid about corporate snooping/tracking so I may stop using it in the near future, but then I think, that's exactly what "they" want me to do.

Now I'm thinking, you're part of the "they" trying to get me to lower my defences....

**Comment by mycumycu** [comment]
"Now I'm thinking, you're part of the "they" trying to get me to lower my defences...." 
You got me here! ;)

This one is some work for a very tiny benefit (from my point of view ofc) - thus I don't see a motivation to implement it. 
Sorry.

**Comment by Menn0x** [comment]
Just had the exact same issue where the console would just close and had no idea wy...came across this post, turned off my VPN and it worked straight away :)

However, I am happy to turn off my VPN when required so not an issue for me.
